#!/bin/sh

fancy_echo() {
	local fmt="$1"; shift

	# shellcheck disable=SC2059
	printf "\n$fmt\n" "$@"
}

append_to_bashrc() {
  local text="$1" bashrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.bashrc.local" ]; then
    bashrc="$HOME/.bashrc.local"
  else
    bashrc="$HOME/.bashrc"
  fi

  if ! grep -Fqs "$text" "$bashrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\n" "$text" >> "$bashrc"
    else
      printf "\n%s\n" "$text" >> "$bashrc"
    fi
  fi
}

mkdir -p $HOME/.bin

case "$SHELL" in
	*/bash) : ;;
	*)
		fancy_echo "Changing your shell to bash ..."
			chsh -s "$(which bash)"
	;;
esac

#################################
# Homebrew functions start here #
#################################
brew_install_or_upgrade() {
  if brew_is_installed "$1"; then
    if brew_is_upgradable "$1"; then
      fancy_echo "Upgrading %s ..." "$1"
      brew upgrade "$@"
    else
      fancy_echo "Already using the latest version of %s. Skipping ..." "$1"
    fi
  else
    fancy_echo "Installing %s ..." "$1"
    brew install "$@"
  fi
}

brew_is_installed() {
  local name="$(brew_expand_alias "$1")"

  brew list -1 | grep -Fqx "$name"
}

brew_is_upgradable() {
  local name="$(brew_expand_alias "$1")"

  ! brew outdated --quiet "$name" >/dev/null
}

brew_tap() {
  brew tap "$1" 2> /dev/null
}

brew_expand_alias() {
  brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}

brew_launchctl_restart() {
  local name="$(brew_expand_alias "$1")"
  local domain="homebrew.mxcl.$name"
  local plist="$domain.plist"

  fancy_echo "Restarting %s ..." "$1"
  mkdir -p "$HOME/Library/LaunchAgents"
  ln -sfv "/usr/local/opt/$name/$plist" "$HOME/Library/LaunchAgents"

  if launchctl list | grep -Fq "$domain"; then
    launchctl unload "$HOME/Library/LaunchAgents/$plist" >/dev/null
  fi
  launchctl load "$HOME/Library/LaunchAgents/$plist" >/dev/null
}
###############################
# Homebrew functions end here #
###############################

######################################
# Homebrew Cask functions start here #
######################################
brew_cask_expand_alias() {
  brew cask info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}

brew_cask_is_installed() {
  local NAME=$(brew_cask_expand_alias "$1")
  brew cask list -1 | grep -Fqx "$NAME"
}

brew_cask_install() {
  if ! brew_cask_is_installed "$1"; then
    brew cask install "$@"
  fi
}

brew_cask_install_or_upgrade() {
  if brew_cask_is_installed "$1"; then
    echo "$1 is already installed, brew cask upgrade is not yet implemented"
  else
    brew cask install "$@"
  fi
}
####################################
# Homebrew Cask functions end here #
####################################

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    append_to_bashrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_bashrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

fancy_echo "Updating Homebrew formulas ..."
brew update

brew_install_or_upgrade 'git'
brew tap caskroom/cask
brew_install_or_upgrade 'brew-cask'
brew_cask_install_or_upgrade 'xquartz'
brew_install_or_upgrade 'cairo'
brew_install_or_upgrade 'node'

#configure apache
sudo sed -i '' '/^#.*mod_vhost_alias.so/ s/^#//' '/private/etc/apache2/httpd.conf'
sudo sed -i '' '/^#.*mod_rewrite.so/ s/^#//' '/private/etc/apache2/httpd.conf'
sudo sed -i '' '/^#.*libphp5.so/ s/^#//' '/private/etc/apache2/httpd.conf'
sudo sed -i '' '/^#.*\/private\/etc\/apache2\/extra\/http-vhosts.conf/ s/^#//' '/private/etc/apache2/httpd.conf'
sudo sed -i '' '/DirectoryIndex index.html/ s//DirectoryIndex index.html index.php/' '/private/etc/apache2/httpd.conf'
sudo apachectl restart

#install and configure mysql
brew_install_or_upgrade 'mysql'
mysql.server start

if [ -f "$HOME/.laptop.local" ]; then
  . "$HOME/.laptop.local"
fi
